# Generated by Django 4.1.2 on 2022-11-05 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medias", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="description",
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
    ]
