# Generated by Django 4.1.2 on 2022-11-17 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medias", "0003_alter_photo_experience_alter_photo_room"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="file",
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name="video",
            name="file",
            field=models.URLField(),
        ),
    ]
